CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    items JSONB NOT NULL DEFAULT '[]',
    user_id TEXT NOT NULL,
    total_cost INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
    key TEXT PRIMARY KEY,
    status_code INTEGER NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);