events { worker_connections 2048; }

http {
    resolver 127.0.0.11 valid=5s;

    server {
        listen 80;

        location /orders/ {
            set $order_upstream http://order-service:5000;
            rewrite ^/orders/(.*) /$1 break;
            proxy_pass         $order_upstream;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 35s;
        }
        location /stock/ {
            set $stock_upstream http://stock-service:5000;
            rewrite ^/stock/(.*) /$1 break;
            proxy_pass         $stock_upstream;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 35s;
        }
        location /payment/ {
            set $payment_upstream http://payment-service:5000;
            rewrite ^/payment/(.*) /$1 break;
            proxy_pass         $payment_upstream;
            proxy_http_version 1.1;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 35s;
        }

        access_log /var/log/nginx/server.access.log;
    }

    access_log /var/log/nginx/access.log;
}
