"""
gateway.py

HTTP gateway — translates incoming REST requests into Kafka messages and
waits synchronously for correlated responses before replying to the client.

Architecture overview
---------------------
Each microservice (orders, stock, payment) consumes directly from its own
Kafka topic. The gateway's sole responsibilities are:

  1. Accept an HTTP request from a client
  2. Assign it a correlation ID
  3. Publish the request envelope to the appropriate service topic
  4. Block until the correlated response arrives on gateway.responses
  5. Return the response to the client

There is no HTTP forwarding layer — the gateway never calls the services
over HTTP. All communication is via Kafka.

Topics produced : gateway.orders, gateway.stock, gateway.payment
Topic consumed  : gateway.responses

Idempotency
-----------
Idempotency keys are an internal concern generated by the services
themselves, not by clients or the gateway. They protect against duplicate
processing when Kafka redelivers a message after a crash. The gateway
strips the Idempotency-Key header if a client sends one — it has no
meaning at the gateway layer and should never reach the services via this
path (services only act on idempotency keys they generated themselves on
the internal Kafka cluster).

Correlation IDs vs idempotency keys
------------------------------------
These are two distinct concepts:

  - Correlation ID: a UUID generated per HTTP request by the gateway.
    Used to match a Kafka response message back to the blocked HTTP thread.
    Has no persistence and no effect on service business logic.

  - Idempotency key: a UUID generated by the order service per saga or
    sub-step. Persisted to the DB. Ensures a DB write is executed exactly
    once even if the Kafka message is redelivered.

Gateway restart behaviour
-------------------------
The response consumer uses auto_offset_reset="latest", meaning it only
reads messages produced after it starts. If the gateway restarts while a
checkout saga is in flight, it will miss the response and the client will
receive a 504. The client should simply retry — the order service persists
saga state to the DB and will either complete the saga and reply, or return
a cached result if it already finished. No data is lost or duplicated.
!TODO update when recovery logging is added. Although gateway should not die, since we also lose HTTP connections then.
"""

import json
import logging
import os
import threading
import uuid
from typing import Any

import kafka
from flask import Flask, Response, abort, jsonify, request
from kafka.admin import NewTopic
from kafka.errors import KafkaError

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

KAFKA_BOOTSTRAP_SERVERS = os.environ.get("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")

# How long the gateway waits for a service response before returning 504.
# Checkout sagas can take longer than simple CRUD operations since they
# involve multiple inter-service round-trips. Set this high enough to
# accommodate the full saga under normal load.
REQUEST_TIMEOUT_S = int(os.environ.get("REQUEST_TIMEOUT_MS", "30000")) / 1000

GATEWAY_TOPICS = ["gateway.orders", "gateway.stock", "gateway.payment"]
RESPONSE_TOPIC = "gateway.responses"

# Headers that must never be forwarded to downstream services.
# Idempotency-Key is excluded because idempotency is an internal concern —
# keys are generated by services, not by clients. Forwarding a client-supplied
# key could cause a service to incorrectly cache a response under a key it
# did not generate, corrupting its idempotency store.
# The hop-by-hop headers are excluded because they are connection-scoped and
# have no meaning once the request is serialised into a Kafka message.
_STRIP_HEADERS = {
    "idempotency-key",
    "host",
    "connection",
    "transfer-encoding",
    "content-length",
}

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask("gateway-service")

# ---------------------------------------------------------------------------
# Kafka helpers
# ---------------------------------------------------------------------------

def _build_producer(bootstrap_servers: str) -> kafka.KafkaProducer:
    return kafka.KafkaProducer(
        bootstrap_servers=bootstrap_servers,
        value_serializer=lambda v: json.dumps(v).encode("utf-8"),
        key_serializer=lambda k: k.encode("utf-8") if k else None,
        acks="all",       # wait for all in-sync replicas — prevents message loss
        retries=3,
        linger_ms=5,      # small batching window; negligible latency cost, meaningful throughput gain
        batch_size=32_768,
    )


def ensure_topics(bootstrap_servers: str, topics: list[str]) -> None:
    """
    Creates any missing Kafka topics at startup. Safe to call on every boot —
    existing topics are left untouched. Failures are logged as warnings rather
    than crashing the process; Kafka may not be ready yet and topics may be
    created by another instance or via infrastructure tooling.
    """
    try:
        admin = kafka.KafkaAdminClient(
            bootstrap_servers=bootstrap_servers,
            request_timeout_ms=10_000,
        )
        existing = set(admin.list_topics())
        missing  = [t for t in topics if t not in existing]
        if missing:
            admin.create_topics(
                [NewTopic(name=t, num_partitions=3, replication_factor=1) for t in missing],
                validate_only=False,
            )
            logger.info("Created Kafka topics: %s", missing)
        admin.close()
    except KafkaError as exc:
        logger.warning("Could not ensure topics exist: %s", exc)

# ---------------------------------------------------------------------------
# KafkaClient — shared response consumer, event-based request unblocking
#
# Flow for a single request:
#
#   1. send_request() registers a threading.Event keyed on correlation_id
#   2. The request payload is published to the service topic
#   3. send_request() blocks on event.wait()
#   4. The background response consumer receives the matching message on
#      gateway.responses and calls event.set()
#   5. send_request() unblocks, retrieves the response, and returns it
#
# A single shared consumer handles all in-flight requests. This avoids the
# O(N) anti-pattern of spinning up one consumer per request, which would
# exhaust Kafka consumer group resources under load and replay the entire
# partition history for every request.
#
# Thread safety: _pending is accessed by both Flask worker threads (via
# send_request) and the response consumer thread (via _handle_response).
# All access is protected by _pending_lock.
#
# Restart behaviour: auto_offset_reset="latest" means the consumer only
# reads messages produced after it subscribes. Responses published while
# the gateway was down are permanently missed — the blocked Flask thread
# will have already timed out and returned 504 to the client anyway, so
# there is no thread to unblock. The client retrying the request is the
# correct recovery path.
# ---------------------------------------------------------------------------

class KafkaClient:

    def __init__(self, bootstrap_servers: str) -> None:
        self.bootstrap_servers = bootstrap_servers
        self._producer         = _build_producer(bootstrap_servers)

        # Maps correlation_id → (Event, response_payload | None).
        # An entry is inserted before publishing and removed after the
        # response is consumed or the wait times out.
        self._pending: dict[str, tuple[threading.Event, dict | None]] = {}
        self._pending_lock = threading.Lock()

        self._start_response_consumer()

    def send_request(
        self,
        topic: str,
        payload: dict[str, Any],
        correlation_id: str,
    ) -> dict[str, Any]:
        """
        Publishes payload to topic and blocks until the correlated response
        arrives, or until REQUEST_TIMEOUT_S elapses (→ 504).
        """
        event = threading.Event()

        # Register before publishing to avoid a race where the response
        # arrives before we have registered the event to receive it.
        with self._pending_lock:
            self._pending[correlation_id] = (event, None)

        try:
            self._producer.send(topic, key=correlation_id, value=payload).get(timeout=10)
        except KafkaError as exc:
            # Remove the pending entry — nothing will arrive for this ID.
            self._remove_pending(correlation_id)
            raise RuntimeError(f"Failed to enqueue message: {exc}") from exc

        if not event.wait(timeout=REQUEST_TIMEOUT_S):
            # Timed out — clean up and let Flask return 504 to the client.
            self._remove_pending(correlation_id)
            abort(504, description="Gateway timeout waiting for service response")

        with self._pending_lock:
            _, response = self._pending.pop(correlation_id)

        return response  # type: ignore[return-value]

    def _remove_pending(self, correlation_id: str) -> None:
        with self._pending_lock:
            self._pending.pop(correlation_id, None)

    def _start_response_consumer(self) -> None:
        """
        Starts a single long-lived daemon thread that consumes gateway.responses.
        If it crashes it logs the error but does not restart automatically —
        all in-flight requests will time out and return 504. In production,
        a process supervisor (e.g. Kubernetes liveness probe) should restart
        the gateway pod in this case.
        """
        def consume() -> None:
            consumer = kafka.KafkaConsumer(
                RESPONSE_TOPIC,
                bootstrap_servers=self.bootstrap_servers,
                group_id="gateway-response-listener",
                auto_offset_reset="latest",
                enable_auto_commit=True,
                value_deserializer=lambda m: json.loads(m.decode("utf-8")),
            )
            logger.info("Response consumer started on '%s'", RESPONSE_TOPIC)
            try:
                for message in consumer:
                    self._handle_response(message.value)
            except Exception as exc:
                logger.error("Response consumer crashed: %s", exc, exc_info=True)
            finally:
                consumer.close()

        threading.Thread(target=consume, daemon=True, name="kafka-response-consumer").start()

    def _handle_response(self, payload: dict[str, Any]) -> None:
        """
        Called by the response consumer thread for every message on
        gateway.responses. If the correlation_id matches a pending request,
        stores the response and unblocks the waiting Flask thread.

        Messages with no matching pending entry are silently dropped — this
        happens normally when a request has already timed out and its entry
        was cleaned up, or when the response belongs to a different gateway
        instance in a horizontally scaled deployment.
        """
        correlation_id = payload.get("correlation_id")
        if not correlation_id:
            return

        with self._pending_lock:
            entry = self._pending.get(correlation_id)
            if entry is None:
                return
            event, _ = entry
            self._pending[correlation_id] = (event, payload)

        # Set the event outside the lock so the Flask thread can acquire
        # the lock immediately when it wakes up.
        event.set()

# ---------------------------------------------------------------------------
# Flask proxy routes
# ---------------------------------------------------------------------------

def _proxy(service_topic: str, subpath: str) -> Response:
    """
    Shared handler for all service proxy routes.

    Builds the request envelope, publishes it to the service topic, and
    blocks until the response arrives. The correlation_id attached by
    _attach_correlation_id is used to match the response.

    The Idempotency-Key header is stripped along with hop-by-hop headers
    before forwarding. See _STRIP_HEADERS and the module docstring for
    the full rationale.
    """
    full_path      = f"/{subpath}" if subpath else "/"
    correlation_id = request.correlation_id  # type: ignore[attr-defined]

    # Strip headers that must not reach the services.
    forwarded_headers = {
        k: v for k, v in request.headers
        if k.lower() not in _STRIP_HEADERS
    }

    payload: dict[str, Any] = {
        "method":          request.method,
        "path":            full_path,
        "correlation_id":  correlation_id,
        "query_params":    dict(request.args),
        "headers":         forwarded_headers,
        "body":            request.get_json(silent=True) or dict(request.form) or None,
    }

    try:
        response = kafka_client.send_request(
            topic=service_topic,
            payload=payload,
            correlation_id=correlation_id,
        )
    except RuntimeError as exc:
        logger.error("Kafka send error for topic '%s': %s", service_topic, exc)
        abort(502, description="Service temporarily unavailable")

    return _build_response(response)


def _build_response(response: dict[str, Any]) -> Response:
    """Converts the service response envelope into a Flask Response."""
    status_code: int = response.get("status_code", 200)
    body: Any        = response.get("body", "")
    headers: dict    = response.get("headers") or {}

    if isinstance(body, (dict, list)):
        return jsonify(body), status_code, headers
    return Response(str(body), status=status_code, headers=headers)


@app.before_request
def _attach_correlation_id() -> None:
    """
    Assigns a unique correlation ID to every inbound request.
    This ID travels with the Kafka message and is used to match the
    response back to the correct blocked Flask thread.
    It is distinct from an idempotency key — it has no effect on service
    business logic and is not persisted anywhere.
    """
    request.correlation_id = str(uuid.uuid4())


METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"]

@app.route("/orders/", defaults={"subpath": ""}, methods=METHODS)
@app.route("/orders/<path:subpath>", methods=METHODS)
def orders_proxy(subpath: str) -> Response:
    return _proxy("gateway.orders", subpath)


@app.route("/stock/", defaults={"subpath": ""}, methods=METHODS)
@app.route("/stock/<path:subpath>", methods=METHODS)
def stock_proxy(subpath: str) -> Response:
    return _proxy("gateway.stock", subpath)


@app.route("/payment/", defaults={"subpath": ""}, methods=METHODS)
@app.route("/payment/<path:subpath>", methods=METHODS)
def payment_proxy(subpath: str) -> Response:
    return _proxy("gateway.payment", subpath)


@app.route("/health")
def health() -> Response:
    return jsonify({"status": "healthy"})

# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    ensure_topics(
        KAFKA_BOOTSTRAP_SERVERS,
        GATEWAY_TOPICS + [RESPONSE_TOPIC],
    )

    # KafkaClient starts its response consumer background thread on init.
    # It must be initialised before Flask starts accepting requests, otherwise
    # the first requests have no consumer to receive their responses.
    kafka_client = KafkaClient(KAFKA_BOOTSTRAP_SERVERS)

    app.run(host="0.0.0.0", port=8000, debug=False)